### ISSUE TITLE
Asynchronous DNS

### ISSUE THREAD

**Issue by tailhook** [murarth/resolve#1]
Hi,

I'm trying to build a composable [I/O framework on top of mio](https://github.com/tailhook/rotor), and no wonder that I want DNS support for it. Would you like to join the effort?

What I'm thinking of, is having separate creates for the following things:
1. `system_files`: Reads system files (nsswitch.conf, hosts, resolv.conf)
2. `dns_proto`: Parses and constructs DNS packets

And probably few different implementations of the real address resolution:
- Synchronous one based on stdlib types
- Async one based on [rotor](https://github.com/tailhook/rotor)
- May be async one based on raw mio that is designed to be put to another thread

Probably some common parts of different implementations may be put to `dns_proto` too.

What to do you think?

**Comment by murarth** [comment]
If you want to use the `resolve` crate, I think it could potentially fulfill your needs, but it does need some work before it can be considered fully featured.

The public API of `resolve` includes facilities for encoding and decoding messages. These operate on individual messages and can be used with any UDP socket implementation. If you want to handle crafting and transport of messages in your own code, `Message::decode` and `Message::encode` may be all you need.

`resolv.conf` support is indeed woefully inadequate and support for other DNS-related configuration files is nonexistent. If you'd prefer to implement system configuration in your own code, you could certainly use `resolve` only for message decoding and encoding. It's also possible that support for these configuration files could be improved within `resolve` and a mechanism could be created to craft and/or modify incoming and outgoing messages according to a `DnsConfig` instance (which exists now, but is quite simple).

I don't see the advantage to making a separate crate for parsing system files unless you intend to implement the logic of these configurations in your own code. Personally, I'd prefer a complete "resolver" abstraction provided by a crate, which `resolve` could provide with some more work.

**Comment by tailhook** [comment]
> I don't see the advantage to making a separate crate for parsing system files unless you intend to implement the logic of these configurations in your own code.

Well, my gut feeling says that it would be nice to have as a separate crate for clarity. But in fact, yes, I need to get logic from the resolv.conf, in particular "options" setting.

And as I see your code has very limited parsing of `resolv.conf` I'd like to make it better from the start (in particular ignoring `domain` and `search` options would be super-surprising for many users).

From skimming the code I also have the following questions:
1. Why don't you use `gethostname` from either `nix` or `libc`? (I'm not sure, does it work on windows?)
2. I believe that idna encoding/decoding should also be in separate crate, because encoding/decoding can be used on it's own without any DNS implementation (or using libc implementation), for example in GUI for displaying names
3. I'm using stable rust, are there any `feature`s that it's hard to get rid of?

**Comment by murarth** [comment]
> Why don't you use `gethostname`

`gethostname` is very restrictive in its functionality. It performs only name resolution (`A` and `AAAA` records) and cannot be used asynchronously. (Unless you count running the function in another thread and delivering the result through a channel, but that's not a good plan for applications which may be making many concurrent DNS requests).

> idna encoding/decoding should also be in separate crate

There are punycode implementations in other crates that didn't quite meet my requirements. If that's the only functionality one needs, it is otherwise available.

> I'm using stable rust, are there any `feature`s that it's hard to get rid of?

It appears that all features could be removed by putting the `resolver` module behind a crate feature, defining our own `IpAddr` type, and some other insignificant changes.

I happen to have some free time right now, so I'll see about making a few of these changes.

**Comment by tailhook** [comment]
> gethostname is very restrictive in its functionality. It performs only name resolution (A and AAAA records) and cannot be used asynchronously

Sorry AFAIK, it does no name resolution, it's simple system call that fetches a name known by system. And there is ffi definition in "libc" crate, and a safe wrapper in "nix" crate, it's probably simpler to use one if them instead of your own ffi definition.

> There are punycode implementations in other crates that didn't quite meet my requirements. If that's the only functionality one needs, it is otherwise available.

Found only one in "url" crate. Can you be a little bit more specific what's wrong with it? (so I could chose one for my needs too :)  )

**Comment by murarth** [comment]
Oh, my mistake. I was thinking of `gethost`**`by`**`name`. I don't see a declaration for `gethostname` in libc. A quick Google search shows that `gethostname` does exist in libc on Windows and with the same signature as POSIX. It seems pretty harmless to me to declare one FFI function.

I don't remember the issue I had with `rust-url`'s punycode implementation. It may have been something very petty.

**Comment by murarth** [comment]
I was mistaken about being able to remove the `ip_addr` feature gate. I gave it a shot, but it's just too deeply embedded in the code right now.

**Comment by murarth** [comment]
It hasn't been thoroughly tested, but I've implemented a few more features of `resolv.conf` into `DnsResolver`. Unfortunately, that API is stuck being synchronous. I'm unsure how to build an API with these features that performs asynchronous requests and can be used from any possible event loop. I'll have to give this some further thought.

**Comment by dimbleby** [comment]
@tailhook: there are a couple of crates available offering asynchronous DNS.  Both are wrappers around C libraries:
- [c-ares](https://crates.io/crates/c-ares) (this one is mine)
- [unbound](https://crates.io/crates/unbound) (this one is not mine)

Depending on what your goals are, these may or may not be interesting to you...

**Comment by tailhook** [comment]
@dimbleby, sure, my goal is to write pure-rust inplementation.

Anyway probably this issue may be closed now.
