### ISSUE TITLE
resolve_host fails

### ISSUE THREAD

**Issue by workanator** [murarth/resolve#12]
Hello,

`resolve_host` fails with error `Invalid argument (os error 22)` on Mac OS X El Captain. It does not matter which host name I try to resolve. Rust version 1.8 and the `resolve` version used is 0.1.1. I know there is not much info for you. How can I help?

**Comment by murarth** [comment]
Is there an OS X equivalent to `strace`? That would be the easiest way of finding which system call is producing the error.

**Comment by workanator** [comment]
There is `dtruss` tool on OS X and you can find the output of it in the attached file [trace.zip](https://github.com/murarth/resolve/files/221455/trace.zip). It seems the source of the error is `sendto` syscall.

I add some debug output to `DnsSocket::send_message` and here is the result.

``` text
send [73, 170, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 6, 103, 111, 111, 103, 108, 101, 3, 99, 111, 109, 5, 108, 111, 99, 97, 108, 0, 0, 1, 0, 1] to V4(192.168.1.1:53)
send [73, 171, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 6, 103, 111, 111, 103, 108, 101, 3, 99, 111, 109, 5, 108, 111, 99, 97, 108, 0, 0, 28, 0, 1] to V4(192.168.1.1:53)
send [73, 172, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 6, 103, 111, 111, 103, 108, 101, 3, 99, 111, 109, 0, 0, 1, 0, 1] to V4(192.168.1.1:53)
send [73, 173, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 6, 103, 111, 111, 103, 108, 101, 3, 99, 111, 109, 0, 0, 28, 0, 1] to V4(192.168.1.1:53)
Cannot resolve host: Invalid argument (os error 22)
```

**Comment by murarth** [comment]
I wonder if it might have to do with `DnsSocket` binding to an IPv6 address, then trying to send to an IPv4 address. I've written a test program you can run to confirm: https://gist.github.com/murarth/84710fbe495cc2faf47ee41924c9f58f

**Comment by workanator** [comment]
Here is the result of your test program run.

``` text
v4 -> v4 Ok(1)
v4 -> v6 Err(Error { repr: Os { code: 22, message: "Invalid argument" } })
v6 -> v4 Err(Error { repr: Os { code: 22, message: "Invalid argument" } })
v6 -> v6 Ok(1)
```

**Comment by murarth** [comment]
Yep. That confirms it. I've pushed a commit that should fix this somewhat. It will be better fixed when Rust 1.9.0 is stable and `UdpSocket::set_only_v6` is available. A configuration consisting of mixed IPv4 and IPv6 nameservers will, unfortunately, still be broken until then.

**Comment by workanator** [comment]
I confirm it works on OS X El Captain now. Thank you.

**Comment by murarth** [comment]
@workanator: I've fixed this the "right" way, using the `net2` crate to set the IPv6-only option to `false`. Can you verify that this solution works on OS X?

**Comment by workanator** [comment]
The solution with `net2` does not work on El Captain. I encounter the same error `Invalid argument (os error 22)`. If the previous patch is platform specific maybe you should use `#[cfg(target_os = "macos", target_os = "ios")]` then?

**Comment by murarth** [comment]
Okay, I guess Mac/BSD are just weird about how they handle IPv6 sockets. I'm not sure if there's a reliable way around it without asking users to change their OS configuration, which is obviously not a reasonable request for a library to make. I think the best option is to revert the `net2` fix and just wait and see if anyone runs into the corner case. Thanks for your continued help with this, @workanator.
