### ISSUE TITLE
Way to filter only IPv4 or only IPv6 addresses?

### ISSUE THREAD

**Issue by swiftcoder** [murarth/resolve#13]

**Comment by dbrgn** [comment]
What are you referring to? What type of lookup?

**Comment by murarth** [comment]
@swiftcoder: If you want to resolve only the IPv4 or IPv6 addresses of a host using `DnsResolver`, you can use the method `DnsResolver::resolve_record` to request `A` or `AAAA` records, respectively.

**Comment by swiftcoder** [comment]
Thanks, that was the missing link.
