### ISSUE TITLE
how to use custom dns server ?

### ISSUE THREAD

**Issue by or2me** [murarth/resolve#15]
could you write a example use a custom config on windows ? Thanks a lot .

**Comment by murarth** [comment]
Thanks for the issue. I've just pushed a commit that adds a new method to help with this and an example to show how it's used. Let me know if this works for you.

**Comment by or2me** [comment]
Thank you very much , but the  "resolver.rs" didnt work correctly on my win10. 
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrParseError(())', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

toolchain version 1.22.1

**Comment by murarth** [comment]
Sorry about that. I've fixed the example now.

**Comment by or2me** [comment]
works very well !
thanks for your patient .
