### ISSUE TITLE
Push a new crates.io release?

### ISSUE THREAD

**Issue by bnewbold** [murarth/resolve#17]
Thanks for your quick turn-around on issue #16!

Could you push a new versioned release to crates.io? I tested with github master (as referenced in the README), but it's vastly safer (and thus rust-idiomatic) to point to a specific version instead of "the most latest commit".

Since 0.1.2, a method ("default_config") has been removed, so bumping to 0.2.x probably makes sense.

**Comment by murarth** [comment]
I've published version 0.2.0 to crates.io.

I've also updated the README to indicate using crates.io. Thanks for the note on that.
