### ISSUE TITLE
ip_addr feature

### ISSUE THREAD

**Issue by tailhook** [murarth/resolve#2]
Well, the feature is removed https://github.com/rust-lang/rust/issues/27801

You mentioned in #1 that feature is "too deep in the code", but now it's gone. Any plans to remove it? Will you use ip crate from @dimbleby?

**Comment by murarth** [comment]
There's some discussion on rust-lang/rust#27705 about bringing `IpAddr` back. Once that issue is decided, if `IpAddr` remains deprecated, I'll change things over to use the `ip` crate.

**Comment by tailhook** [comment]
Understood.
