### ISSUE TITLE
Custom lookups

### ISSUE THREAD

**Issue by dbrgn** [murarth/resolve#3]
Would be great if you could add an example on how to query a TXT or SRV record. Right now it looks like that's a pretty low-level operation that requires to construct custom messages and questions.

**Comment by murarth** [comment]
I've added support for SRV records and added the method `resolve_record` to `DnsResolver` to retrieve a set of any type of record. The new example `lookup_srv` demonstrates the use of both.

**Comment by dbrgn** [comment]
Wow, that was fast. Fantastic, thanks a lot for the implementation and the example :)

Right now I'm using an implementation that calls out to the `dig +short` command in my project, but as soon as `time2` is stabilized I'll switch to resolve.

**Comment by dbrgn** [comment]
(I think this can now be closed, right?)
