### ISSUE TITLE
IDNA NamePrep

### ISSUE THREAD

**Issue by SimonSapin** [murarth/resolve#4]
This crate implements IDNA with Punycode, but seems to be missing the "Nameprep" part. rust-url has that in a module: https://github.com/servo/rust-url/blob/master/src/idna.rs If you’re interested this could be a separate crate.

**Comment by murarth** [comment]
Yes, I would be interested. That would be great.

**Comment by SimonSapin** [comment]
Alright, https://crates.io/crates/idna is published with the source currently at https://github.com/servo/rust-url/tree/idna-crate/idna

It currently doesn’t use `Cow::Borrowed` to avoid copying when possible like your module does, but that should be possible to add.
